"""Closure generation and estimation for a finite catalogue prior."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import numpy as np
import pandas as pd
import torch

from .catalogue_likelihood import CatalogueLikelihood, CatalogueScore
from .scene_prior import SHEAR_TRANSFORM
from .shear_map import apply_shear_to_ellipticity


@dataclass(frozen=True)
class MockCatalogue:
    """Detected mock measurements and the random choices that generated them."""

    measurements: pd.DataFrame
    truth: pd.DataFrame

    def __post_init__(self):
        if not len(self.measurements) or len(self.measurements) != len(self.truth):
            raise ValueError("mock measurements and truth must be non-empty and aligned")
        if "mock_kind" in self.truth:
            kinds = self.truth["mock_kind"].drop_duplicates()
            if len(kinds) != 1 or kinds.iloc[0] not in {"likelihood", "image"}:
                raise ValueError(
                    "mock_kind must be constant and equal to 'likelihood' or 'image'"
                )
        if "shear_transform" in self.truth:
            transforms = self.truth["shear_transform"].drop_duplicates()
            if len(transforms) != 1:
                raise ValueError("shear_transform must be constant within a mock")

    @property
    def kind(self) -> str:
        """Return the mock provenance class.

        Frozen mocks written before image closure existed have no ``mock_kind``
        column.  They are likelihood-generated by construction, so retaining
        that interpretation preserves their byte-level reproducibility.
        """

        if "mock_kind" not in self.truth:
            return "likelihood"
        return str(self.truth["mock_kind"].iloc[0])

    @property
    def shear_transform(self) -> Optional[str]:
        """Return the declared forward shear convention, if recorded."""

        if "shear_transform" not in self.truth:
            return None
        return str(self.truth["shear_transform"].iloc[0])

    def save(self, path: str | Path) -> None:
        root = Path(path)
        root.mkdir(parents=True, exist_ok=True)
        self.measurements.to_parquet(root / "measurements.parquet", index=False)
        self.truth.to_parquet(root / "truth.parquet", index=False)

    @classmethod
    def load(cls, path: str | Path) -> "MockCatalogue":
        root = Path(path)
        return cls(
            pd.read_parquet(root / "measurements.parquet"),
            pd.read_parquet(root / "truth.parquet"),
        )


@dataclass(frozen=True)
class ClosureResult:
    """One directional Newton closure estimate."""

    injected_shear: float
    evaluation_shear: float
    estimated_shear: float
    fisher_estimated_shear: float
    n_detected: int
    score_sum: float
    information_sum: float
    score_square_sum: float
    score_z: float
    robust_standard_error: float
    model_standard_error: float
    closure_pull: float
    mean_detection_probability: Optional[float]


def generate_mock_catalogue(
    likelihood: CatalogueLikelihood,
    *,
    n_detected: int,
    g1: float,
    g2: float,
    scene_seed: int,
    detection_seed: int,
    flow_seed: int,
    candidate_batch: Optional[int] = None,
    max_candidates: Optional[int] = None,
) -> MockCatalogue:
    """Generate retained measurements from the same declared likelihood.

    Random streams are deliberately separate so changing the proposal or
    measurement implementation cannot silently reshuffle prior atoms or
    detection uniforms.  With measured selection enabled, the order is scene
    draw, Bernoulli detection, conditional-flow draw, then the deterministic
    output cut.  This is the same detected-and-selected population normalized
    by :class:`CatalogueLikelihood`.
    """

    if n_detected <= 0:
        raise ValueError("n_detected must be positive")
    scene_rng = np.random.default_rng(scene_seed)
    detection_rng = np.random.default_rng(detection_seed)
    batch = int(candidate_batch or max(256, 2 * n_detected))
    limit = int(max_candidates or max(10000, 100 * n_detected))
    view = likelihood.cache.get(g1, g2)
    weights = likelihood.cache.prior.weights

    accepted_rows: list[np.ndarray] = []
    accepted_uniforms: list[np.ndarray] = []
    n_candidates = 0
    n_accept = 0
    if likelihood.selection is None:
        # Preserve the original uncut random stream exactly.  Existing frozen
        # closure mocks and their hashes must not move because selection support
        # was added to the same generator.
        while n_accept < n_detected and n_candidates < limit:
            draw_count = min(batch, limit - n_candidates)
            rows = scene_rng.choice(len(weights), size=draw_count, replace=True, p=weights)
            uniforms = detection_rng.random(draw_count)
            keep = uniforms < view.detection_probability[rows]
            accepted_rows.append(rows[keep])
            accepted_uniforms.append(uniforms[keep])
            n_accept += int(keep.sum())
            n_candidates += draw_count
        if n_accept < n_detected:
            raise RuntimeError(
                f"only {n_accept} detections after {n_candidates} candidates; "
                "check classifier support or raise max_candidates"
            )
        rows = np.concatenate(accepted_rows)[:n_detected]
        uniforms = np.concatenate(accepted_uniforms)[:n_detected]
        condition = view.flow.iloc[rows].reset_index(drop=True)
        torch.manual_seed(int(flow_seed))
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(int(flow_seed))
        samples = likelihood.flow_model.sample(condition, n_samples=1)[:, 0, :]
        if likelihood.shape_target_indices is not None:
            first, second = likelihood.shape_target_indices
            samples = np.asarray(samples).copy()
            samples[:, first] += view.blend_shift[rows, 0]
            samples[:, second] += view.blend_shift[rows, 1]
    else:
        accepted_measurements: list[np.ndarray] = []
        torch.manual_seed(int(flow_seed))
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(int(flow_seed))
        while n_accept < n_detected and n_candidates < limit:
            draw_count = min(batch, limit - n_candidates)
            rows = scene_rng.choice(len(weights), size=draw_count, replace=True, p=weights)
            uniforms = detection_rng.random(draw_count)
            detected = uniforms < view.detection_probability[rows]
            detected_rows = rows[detected]
            detected_uniforms = uniforms[detected]
            if len(detected_rows):
                condition = view.flow.iloc[detected_rows].reset_index(drop=True)
                draws = likelihood.flow_model.sample(condition, n_samples=1)[:, 0, :]
                if likelihood.shape_target_indices is not None:
                    first, second = likelihood.shape_target_indices
                    draws = np.asarray(draws).copy()
                    draws[:, first] += view.blend_shift[detected_rows, 0]
                    draws[:, second] += view.blend_shift[detected_rows, 1]
                selected = np.asarray(
                    likelihood.selection.output_cut(draws), dtype=bool
                )
                if selected.shape != (len(draws),):
                    raise ValueError(
                        "selection cut returned the wrong mock-measurement shape"
                    )
                accepted_rows.append(detected_rows[selected])
                accepted_uniforms.append(detected_uniforms[selected])
                accepted_measurements.append(draws[selected])
                n_accept += int(selected.sum())
            n_candidates += draw_count
        if n_accept < n_detected:
            raise RuntimeError(
                f"only {n_accept} detected-and-selected objects after "
                f"{n_candidates} candidates; check cut support or raise max_candidates"
            )
        rows = np.concatenate(accepted_rows)[:n_detected]
        uniforms = np.concatenate(accepted_uniforms)[:n_detected]
        samples = np.concatenate(accepted_measurements, axis=0)[:n_detected]
    measurements = pd.DataFrame(samples, columns=likelihood.target_names)
    response = likelihood.cache.blend_response
    r_blend = (
        np.zeros(len(rows), dtype=np.float64)
        if response is None
        else response.values[rows]
    )
    truth = pd.DataFrame(
        {
            "scene_row": rows,
            "detection_uniform": uniforms,
            "detection_probability": view.detection_probability[rows],
            "r_blend": r_blend,
            "blend_shift_g1": view.blend_shift[rows, 0],
            "blend_shift_g2": view.blend_shift[rows, 1],
            "shear_transform": SHEAR_TRANSFORM,
            "injected_g1": float(g1),
            "injected_g2": float(g2),
            "scene_seed": int(scene_seed),
            "detection_seed": int(detection_seed),
            "flow_seed": int(flow_seed),
        }
    )
    return MockCatalogue(measurements, truth)


def generate_ring_mock_catalogue(
    likelihood: CatalogueLikelihood,
    base_mock: MockCatalogue,
    *,
    g1: float,
    g2: float,
    orientation_seed: int,
    flow_seed: int,
) -> MockCatalogue:
    """Generate a two-member rotational ring from fixed detected scene rows.

    Each detected base row supplies its spin-0 properties and ellipticity
    amplitude.  A uniform orientation and its 90-degree rotated partner
    (``e -> -e`` in spin-2 coordinates) are then sheared and passed through
    independent flow latents.  Reusing the same seeds at ``+g`` and ``-g``
    makes the two shear arms pathwise paired, while the ring cancels most
    intrinsic-shape variance.  Detection must already be known to be
    shear-invariant; this helper deliberately does not re-run it.
    """

    if likelihood.selection is not None:
        raise ValueError("ring closure currently requires measured cuts disabled")
    if likelihood.cache.blend_response is not None:
        raise ValueError("ring closure currently requires external R_blend=0")
    required = {"scene_row", "detection_uniform", "detection_probability"}
    missing = sorted(required - set(base_mock.truth))
    if missing:
        raise KeyError(f"base mock lacks ring provenance columns: {missing}")
    likelihood.cache.validate_detection_shear_invariance()
    rows = base_mock.truth["scene_row"].to_numpy(dtype=np.int64)
    zero = likelihood.cache.get(0.0, 0.0)
    base_flow = zero.flow.iloc[rows].reset_index(drop=True)
    if not {"e1_input_p", "e2_input_p"} <= set(base_flow):
        raise KeyError("ring closure requires primary ellipticity flow inputs")
    amplitude = np.hypot(
        base_flow["e1_input_p"].to_numpy(dtype=float),
        base_flow["e2_input_p"].to_numpy(dtype=float),
    )
    phase = np.random.default_rng(int(orientation_seed)).uniform(
        0.0, 2.0 * np.pi, size=len(rows)
    )
    first_e1 = amplitude * np.cos(phase)
    first_e2 = amplitude * np.sin(phase)

    sample_parts = []
    truth_parts = []
    for member, sign in enumerate((1.0, -1.0)):
        intrinsic_e1 = sign * first_e1
        intrinsic_e2 = sign * first_e2
        sheared_e1, sheared_e2 = apply_shear_to_ellipticity(
            intrinsic_e1, intrinsic_e2, float(g1), float(g2)
        )
        condition = base_flow.copy()
        condition["e1_input_p"] = sheared_e1
        condition["e2_input_p"] = sheared_e2
        member_flow_seed = int(flow_seed) + member
        torch.manual_seed(member_flow_seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(member_flow_seed)
        samples = likelihood.flow_model.sample(condition, n_samples=1)[:, 0, :]
        sample_parts.append(np.asarray(samples))
        truth_parts.append(
            pd.DataFrame(
                {
                    "scene_row": rows,
                    "ring_id": np.arange(len(rows), dtype=np.int64),
                    "ring_member": member,
                    "intrinsic_e1": intrinsic_e1,
                    "intrinsic_e2": intrinsic_e2,
                    "detection_uniform": base_mock.truth[
                        "detection_uniform"
                    ].to_numpy(dtype=float),
                    "detection_probability": base_mock.truth[
                        "detection_probability"
                    ].to_numpy(dtype=float),
                    "r_blend": 0.0,
                    "blend_shift_g1": 0.0,
                    "blend_shift_g2": 0.0,
                    "shear_transform": SHEAR_TRANSFORM,
                    "injected_g1": float(g1),
                    "injected_g2": float(g2),
                    "scene_seed": base_mock.truth["scene_seed"].to_numpy(),
                    "detection_seed": base_mock.truth[
                        "detection_seed"
                    ].to_numpy(),
                    "flow_seed": member_flow_seed,
                    "orientation_seed": int(orientation_seed),
                    "mock_kind": "likelihood",
                }
            )
        )
    return MockCatalogue(
        pd.DataFrame(
            np.concatenate(sample_parts, axis=0), columns=likelihood.target_names
        ),
        pd.concat(truth_parts, ignore_index=True),
    )


def run_exact_closure(
    likelihood: CatalogueLikelihood,
    mock: MockCatalogue,
    *,
    center: Sequence[float] = (0.0, 0.0),
    direction: Sequence[float] = (1.0, 0.0),
    delta: float = 0.01,
    richardson: bool = True,
    object_chunk: int = 64,
    atom_chunk: int = 4096,
) -> ClosureResult:
    """Score a mock catalogue against every finite prior atom."""

    score = likelihood.score_and_information(
        mock.measurements,
        center=center,
        direction=direction,
        delta=delta,
        richardson=richardson,
        object_chunk=object_chunk,
        atom_chunk=atom_chunk,
    )
    direction_array = np.asarray(direction, dtype=float)
    direction_array /= np.linalg.norm(direction_array)
    evaluation_shear = float(np.asarray(center, dtype=float) @ direction_array)
    return summarize_closure_score(
        mock,
        score,
        direction=direction,
        evaluation_shear=evaluation_shear,
    )


def summarize_closure_score(
    mock: MockCatalogue,
    score: CatalogueScore,
    *,
    direction: Sequence[float] = (1.0, 0.0),
    evaluation_shear: float = 0.0,
) -> ClosureResult:
    """Turn one already-evaluated directional score into a closure result."""

    direction = np.asarray(direction, dtype=float)
    norm = float(np.linalg.norm(direction))
    if direction.shape != (2,) or norm == 0:
        raise ValueError("direction must be a nonzero two-vector")
    direction = direction / norm
    injected_vector = mock.truth[["injected_g1", "injected_g2"]].iloc[0].to_numpy(float)
    injected = float(injected_vector @ direction)
    evaluation_shear = float(evaluation_shear)
    if not np.isfinite(evaluation_shear):
        raise ValueError("evaluation_shear must be finite")
    score_sum = float(score.score.sum())
    information_sum = float(score.information.sum())
    score_square_sum = float(np.square(score.score).sum())
    if not np.isfinite(information_sum) or information_sum == 0:
        raise RuntimeError("summed observed information is zero or non-finite")
    if not np.isfinite(score_square_sum) or score_square_sum == 0:
        raise RuntimeError("summed squared score is zero or non-finite")
    estimate = evaluation_shear + score_sum / information_sum
    fisher_estimate = evaluation_shear + score_sum / score_square_sum
    score_z = score_sum / np.sqrt(score_square_sum)
    n = len(score.score)
    if n < 2:
        robust_standard_error = float("nan")
    else:
        # Delta-method (sandwich) uncertainty for the ratio estimator
        # sum(s_i) / sum(I_i).  The residuals sum to zero by construction;
        # n/(n-1) supplies the usual finite-sample variance correction.
        offset = estimate - evaluation_shear
        residual = np.asarray(score.score, dtype=float) - offset * np.asarray(
            score.information, dtype=float
        )
        robust_variance = (
            n / (n - 1) * float(np.square(residual).sum()) / information_sum**2
        )
        robust_standard_error = float(np.sqrt(robust_variance))
    model_standard_error = (
        float(1.0 / np.sqrt(information_sum))
        if information_sum > 0
        else float("nan")
    )
    closure_pull = (
        float((estimate - injected) / robust_standard_error)
        if np.isfinite(robust_standard_error) and robust_standard_error > 0
        else float("nan")
    )
    return ClosureResult(
        injected_shear=injected,
        evaluation_shear=evaluation_shear,
        estimated_shear=estimate,
        fisher_estimated_shear=fisher_estimate,
        n_detected=n,
        score_sum=score_sum,
        information_sum=information_sum,
        score_square_sum=score_square_sum,
        score_z=score_z,
        robust_standard_error=robust_standard_error,
        model_standard_error=model_standard_error,
        closure_pull=closure_pull,
        mean_detection_probability=(
            float(mock.truth["detection_probability"].mean())
            if "detection_probability" in mock.truth
            else None
        ),
    )


__all__ = [
    "ClosureResult",
    "MockCatalogue",
    "generate_mock_catalogue",
    "generate_ring_mock_catalogue",
    "run_exact_closure",
    "summarize_closure_score",
]
