"""Conditional density model for selected measured catalogue properties.

The measurement model represents the normalized likelihood

    p_meas(xhat | truth, neighbour, shear, s=1)

for rows that already satisfy the current SBSI source cuts and selection event.
It intentionally does not include the Bernoulli selection factor; compose this
with the selection classifier when using the unnormalized catalogue density.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Optional, Sequence

import numpy as np
import pandas as pd
import torch
from torch import nn

from .nn_utils import activation_class as _activation
from .coordinates import angle_to_radians
from .selection_model import (
    DEFAULT_SELECTION_FEATURES,
    SHEARFREE_G0_SELECTION_FEATURES,
    TabularPreprocessor,
)


DEFAULT_MEASUREMENT_CONDITION_FEATURES = [
    *DEFAULT_SELECTION_FEATURES,
    "redshift_input_p",
    "redshift_input_s_blend",
]

# Shear-free conditioning for the refined g=0 forward model (SBI_shear.md §2/§4).
# Same logic as the selection model: trained on g=0 only, no applied-shear inputs;
# redshift is kept because redshift-aware blending is the project differentiator.
SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES = [
    *SHEARFREE_G0_SELECTION_FEATURES,
    "redshift_input_p",
    "redshift_input_s_blend",
]

# ORIENTED variant for the measurement flow.  Unlike selection (where the detection
# probability is ~orientation-independent and the rotation-invariant `e_abs_p` is fine),
# the measured target `measured_e1/e2_image` is orientation-full: shear acts on the
# primary shape's *direction*, so the conditioning must keep it.  We therefore replace
# the rotation-invariant `e_abs_p` with the oriented sky-basis components
# `e1_input_p, e2_input_p`.  Validated by the held-out-shear recovery test: with
# `e_abs_p` the recovered shear is ~10x too small; the orientation must be restored.
SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_ORIENTED = [
    "Re_input_p_scaled",
    "r_input_p_scaled",
    "sersic_n_input_p",
    "e1_input_p",
    "e2_input_p",
    "neighbored",
    "distance_scaled_blend",
    "pair_pframe_cos2_blend",
    "pair_pframe_sin2_blend",
    "Re_input_s_scaled_blend",
    "r_input_s_scaled_blend",
    "flux_ratio_blend",
    "sersic_n_input_s_blend",
    "e_pframe_parallel_s_blend",
    "e_pframe_cross_s_blend",
    "redshift_input_p",
    "redshift_input_s_blend",
]

# CROWDING variants: drop the single-pair neighbour block entirely and replace it with a
# COMPACT crowding summary. Motivation: both NP7 (nearest-pair) and AP7 (all-pairs) flows
# mis-predict the self-response by +13% to -66% across crowding (blind to neighbour
# MULTIPLICITY). These sets condition on own props + a crowding scalar the pair block lacks.
_CROWD_OWN = [
    "Re_input_p_scaled", "r_input_p_scaled", "sersic_n_input_p",
    "e1_input_p", "e2_input_p", "redshift_input_p",
]
# (1) distance-shell total neighbour flux (keeps separation that a single total-flux loses)
SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_FLUX = [
    *_CROWD_OWN, "nbr_flux_near", "nbr_flux_far",
]
# (2) emulator's per-galaxy summed blending response as a single crowding scalar
SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_RBLEND = [
    *_CROWD_OWN, "r_blend",
]
SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_FLUX_RBLEND = [
    *_CROWD_OWN, "nbr_flux_near", "nbr_flux_far", "r_blend",
]
# (3) shell flux + brightest-single-neighbour flux = a CONCENTRATION signal. The confirm-first
# orthogonality test (WORKLOG cont.15) showed the self-response deficit varies with flux
# concentration (one bright close blend vs many faint) at FIXED nbr_flux_near/far, i.e. the flow
# is blind to dominance. nbr_flux_max supplies it geometrically (pure truth, no emulator coupling).
SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_FLUX_CONC = [
    *_CROWD_OWN, "nbr_flux_near", "nbr_flux_far", "nbr_flux_max",
]

# REALISTIC conditioning (WORKLOG cont.19): the flow object is p(ehat, thetahat | e, theta,
# theta_blending). Real data has only MEASURED (noisy) properties for the detected PRIMARY, so its
# own-props move true->measured. KEY: intrinsic e1/e2_input_p are the true latent `e` and the ONLY
# shear-map channel (R_flow is generated by reshearing them in the flow-blind mean head); they are
# KEPT (mean-head-only via --flow-blind-features), NOT the banned measured shape. Only the shear-SAFE
# (shear-even) primary observables are swapped: true r_input_p_scaled -> measured_mag_auto (flux/mag),
# true Re_input_p_scaled -> measured_flux_radius (round/area size; a_image/b_image are O(g) unsafe).
# Neighbours (theta_blending) stay TRUE per directive: nbr_flux_near/far/max.
_MEAS_CROWD_NBR = ["nbr_flux_near", "nbr_flux_far", "nbr_flux_max"]
# V1 (bridge): swap ONLY size+flux true->measured; keep sersic_n + redshift TRUE. Isolates the
# measurement-noise cost of the size+flux axis (vs conc-v1) with everything else held true.
SHEARFREE_G0_MEAS_CROWD_CONC_SZFL = [
    "e1_input_p", "e2_input_p", "sersic_n_input_p", "redshift_input_p",
    "measured_mag_auto", "measured_flux_radius", *_MEAS_CROWD_NBR,
]
# V1-noz (WORKLOG cont.35): V1 minus TRUE redshift. redshift is not an imaging observable (no real
# pipeline has true per-object z at measurement time) and injects the sim's n(z) as a prior into the
# calibration; it is a shear-even scatter conditioner, not a response channel. Keep TRUE sersic_n so
# this is a CLEAN one-feature ablation vs V1 (unlike V2, which dropped sersic_n+z and added class_star).
SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ = [
    "e1_input_p", "e2_input_p", "sersic_n_input_p",
    "measured_mag_auto", "measured_flux_radius", *_MEAS_CROWD_NBR,
]
# V2.8 one-scalar ablation: expose the same continuous summed BlendEMU response
# that already defines V2.2's response-target crowd axis.  The final model still
# adds R_blend separately; here it is only scene context for the self-response
# flow.  Retaining near/far/max makes this an append-only comparison to V2.2.
SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_RBLEND = [
    *SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ, "r_blend",
]
# V2.3 scene-context probe: V2/V2.2's near/far/MAX block cannot distinguish
# the flux in the two brightest neighbours from flux in the third and later
# neighbours. Half-shear cases 40--199 show a 2.26+-0.46 point SELF-response
# contrast along that missing direction even after all existing inputs are
# balanced. This one additional pure-input scalar names that direction; no
# constgold response or fitted correction enters it.
SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_THIRDPLUS = [
    *SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ, "nbr_flux_thirdplus",
]
# V2.6 scene decomposition: name both the leading two-neighbour flux and the
# remaining scene flux explicitly.  The controlled half-shear diagnostic fixes
# the former while varying the latter; using both prevents the marginal scene
# trend from being attributed twice to third-plus flux.
SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_TOP2_THIRDPLUS = [
    *SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ, "nbr_flux_top2", "nbr_flux_thirdplus",
]
# V2.7 radial-scene probes.  These are deterministic intrinsic-scene inputs:
# absolute neighbour flux in six disjoint annuli, or Eq. 17 image-overlap
# blendedness.  They deliberately retain every V2.2 conditioner so the two
# arms change only the proposed scene representation.
V27_SIX_SHELL_FEATURES = [
    "logflux_abs_shell_0_0p5", "logflux_abs_shell_0p5_1",
    "logflux_abs_shell_1_2", "logflux_abs_shell_2_3",
    "logflux_abs_shell_3_5", "logflux_abs_shell_5_10",
]
SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_SIXSHELL = [
    *SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ, *V27_SIX_SHELL_FEATURES,
]
SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_PURITY = [
    *SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ, "true_blendedness_eq17",
]
# V2 (realistic): full measured primary own-props. DROP sersic_n + redshift (no shear-safe measured
# substitute; they are scatter conditioners, NOT response channels) and add measured_class_star as a
# noisy profile/concentration proxy. This is the target p(ehat,thetahat|e,theta,theta_blending).
SHEARFREE_G0_MEAS_CROWD_CONC_FULL = [
    "e1_input_p", "e2_input_p",
    "measured_mag_auto", "measured_flux_radius", "measured_class_star", *_MEAS_CROWD_NBR,
]
# ROUND 2 (WORKLOG cont.20): V2/full failed on global slope (in-train -1.21%) while V1/szfl passed
# (+0.03%), isolating the loss to DROPPING true sersic_n + redshift, not to size/flux measurement noise.
# The next three variants (a) diagnose WHICH true structural axis is load-bearing and (b) test whether a
# fully-realistic (all-measured) concentration proxy can recover it. All share V2's realistic base.
_MEAS_V2_BASE = ["measured_mag_auto", "measured_flux_radius", "measured_class_star", *_MEAS_CROWD_NBR]
# Historical structure diagnostic: V2 + true sersic_n only (redshift dropped).
SHEARFREE_G0_MEAS_CONC_SERN = ["e1_input_p", "e2_input_p", "sersic_n_input_p", *_MEAS_V2_BASE]
# Historical structure diagnostic: V2 + true redshift only (sersic_n dropped).
SHEARFREE_G0_MEAS_CONC_Z = ["e1_input_p", "e2_input_p", "redshift_input_p", *_MEAS_V2_BASE]
# V4 realistic recovery: V2 + MEASURED structure proxies (mag_aper, fwhm_image, isoarea_image). The
# mean-head can form concentration ~ mag_aper - mag_auto; fully measured -> deployable on real data.
SHEARFREE_G0_MEAS_CONC_STRUCT = [
    "e1_input_p", "e2_input_p", *_MEAS_V2_BASE,
    "measured_mag_aper", "measured_fwhm_image", "measured_isoarea_image",
]

MEASUREMENT_CONDITION_FEATURE_SETS = {
    "v6_primary_frame": DEFAULT_MEASUREMENT_CONDITION_FEATURES,
    "g0_shearfree": SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES,
    "g0_oriented": SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_ORIENTED,
    "g0_crowd_flux": SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_FLUX,
    "g0_crowd_rblend": SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_RBLEND,
    "g0_crowd_flux_rblend": SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_FLUX_RBLEND,
    "g0_crowd_flux_conc": SHEARFREE_G0_MEASUREMENT_CONDITION_FEATURES_CROWD_FLUX_CONC,
    "g0_meas_crowd_conc_szfl": SHEARFREE_G0_MEAS_CROWD_CONC_SZFL,
    "g0_meas_crowd_conc_szfl_noz": SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ,
    "g0_meas_crowd_conc_szfl_noz_rblend":
        SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_RBLEND,
    "g0_meas_crowd_conc_szfl_noz_thirdplus":
        SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_THIRDPLUS,
    "g0_meas_crowd_conc_szfl_noz_top2_thirdplus":
        SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_TOP2_THIRDPLUS,
    "g0_meas_crowd_conc_szfl_noz_sixshell":
        SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_SIXSHELL,
    "g0_meas_crowd_conc_szfl_noz_purity":
        SHEARFREE_G0_MEAS_CROWD_CONC_SZFL_NOZ_PURITY,
    "g0_meas_crowd_conc_full": SHEARFREE_G0_MEAS_CROWD_CONC_FULL,
    "g0_meas_conc_sern": SHEARFREE_G0_MEAS_CONC_SERN,
    "g0_meas_conc_z": SHEARFREE_G0_MEAS_CONC_Z,
    "g0_meas_conc_struct": SHEARFREE_G0_MEAS_CONC_STRUCT,
}

DEFAULT_MEASUREMENT_TARGETS = [
    "measured_log_flux_auto",
    "measured_log_flux_radius",
    "measured_log_a_image",
    "measured_log_b_image",
    "measured_e1_image",
    "measured_e2_image",
]

_ENGINEERED_TARGET_RAW_COLUMNS = {
    "measured_log_flux_auto": {"measured_flux_auto"},
    "measured_log_flux_radius": {"measured_flux_radius"},
    "measured_log_a_image": {"measured_a_image"},
    "measured_log_b_image": {"measured_b_image"},
    "measured_e1_image": {"measured_a_image", "measured_b_image", "measured_theta_image"},
    "measured_e2_image": {"measured_a_image", "measured_b_image", "measured_theta_image"},
}


def _safe_log_positive(values):
    values = np.asarray(values, dtype=float)
    out = np.full(values.shape, np.nan, dtype=float)
    good = np.isfinite(values) & (values > 0.0)
    out[good] = np.log(values[good])
    return out


def raw_columns_for_measurement_targets(targets: Iterable[str]) -> set[str]:
    """Return catalogue columns needed before target feature engineering."""
    columns: set[str] = set()
    for name in targets:
        if name in _ENGINEERED_TARGET_RAW_COLUMNS:
            columns.update(_ENGINEERED_TARGET_RAW_COLUMNS[name])
        else:
            columns.add(name)
    return columns


def add_measurement_target_features(frame: pd.DataFrame) -> pd.DataFrame:
    """Add stable continuous measured-property targets in-place and return frame."""
    if "measured_flux_auto" in frame.columns:
        frame["measured_log_flux_auto"] = _safe_log_positive(frame["measured_flux_auto"].array)
    if "measured_flux_radius" in frame.columns:
        frame["measured_log_flux_radius"] = _safe_log_positive(frame["measured_flux_radius"].array)
    if "measured_a_image" in frame.columns:
        frame["measured_log_a_image"] = _safe_log_positive(frame["measured_a_image"].array)
    if "measured_b_image" in frame.columns:
        frame["measured_log_b_image"] = _safe_log_positive(frame["measured_b_image"].array)

    needed = {"measured_a_image", "measured_b_image", "measured_theta_image"}
    if needed.issubset(frame.columns):
        a = np.asarray(frame["measured_a_image"], dtype=float)
        b = np.asarray(frame["measured_b_image"], dtype=float)
        theta = angle_to_radians(frame["measured_theta_image"].array)
        denom = a + b
        eps = np.full(len(frame), np.nan, dtype=float)
        good = (
            np.isfinite(a)
            & np.isfinite(b)
            & np.isfinite(theta)
            & (a > 0.0)
            & (b > 0.0)
            & np.isfinite(denom)
            & (denom > 0.0)
        )
        eps[good] = (a[good] - b[good]) / denom[good]
        frame["measured_e1_image"] = eps * np.cos(2.0 * theta)
        frame["measured_e2_image"] = eps * np.sin(2.0 * theta)
    return frame


@dataclass
class TargetStandardizer:
    target_names: list[str]
    means: np.ndarray
    scales: np.ndarray

    @classmethod
    def fit(cls, frame: pd.DataFrame, target_names: Sequence[str]):
        missing = [name for name in target_names if name not in frame.columns]
        if missing:
            raise KeyError(f"Missing target columns: {missing}")
        values = frame[list(target_names)].to_numpy(dtype=np.float32, copy=True)
        finite = np.isfinite(values)
        if not np.all(finite):
            bad = {
                name: int((~finite[:, i]).sum())
                for i, name in enumerate(target_names)
                if np.any(~finite[:, i])
            }
            raise ValueError(f"Cannot fit target transform with non-finite values: {bad}")
        means = values.mean(axis=0, dtype=np.float64).astype(np.float32)
        scales = values.std(axis=0, ddof=1).astype(np.float32)
        scales[~np.isfinite(scales) | (scales < 1e-6)] = 1.0
        return cls(list(target_names), means, scales)

    @property
    def dim(self):
        return len(self.target_names)

    def transform_frame(self, frame: pd.DataFrame):
        raw = frame[self.target_names].to_numpy(dtype=np.float32, copy=True)
        return self.transform_array(raw)

    def transform_array(self, values):
        values = np.asarray(values, dtype=np.float32)
        return ((values - self.means) / self.scales).astype(np.float32, copy=False)

    def inverse_transform_array(self, values):
        values = np.asarray(values, dtype=np.float32)
        return (values * self.scales + self.means).astype(np.float32, copy=False)

    def to_state(self):
        return {
            "target_names": self.target_names,
            "means": self.means,
            "scales": self.scales,
        }

    @classmethod
    def from_state(cls, state):
        return cls(
            list(state["target_names"]),
            np.asarray(state["means"], dtype=np.float32),
            np.asarray(state["scales"], dtype=np.float32),
        )


class ConditionalAffineCoupling(nn.Module):
    def __init__(
        self,
        target_dim,
        context_dim,
        hidden_dim=256,
        n_layers=3,
        mask=None,
        scale_limit=3.0,
        activation="silu",
    ):
        super().__init__()
        if n_layers < 1:
            raise ValueError("n_layers must be >= 1")
        if mask is None:
            mask = self._alternating_mask(target_dim)
        mask = torch.as_tensor(mask, dtype=torch.float32)
        if mask.numel() != target_dim:
            raise ValueError("mask length must match target_dim")
        if float(mask.sum()) <= 0.0 or float(mask.sum()) >= float(target_dim):
            raise ValueError("coupling mask must leave at least one identity and transformed dimension")
        self.register_buffer("mask", mask)
        self.scale_limit = float(scale_limit)

        act = _activation(activation)
        layers = []
        dim = target_dim + context_dim
        for _ in range(n_layers):
            layers.append(nn.Linear(dim, hidden_dim))
            layers.append(act())
            dim = hidden_dim
        layers.append(nn.Linear(dim, 2 * target_dim))
        self.net = nn.Sequential(*layers)
        nn.init.zeros_(self.net[-1].weight)
        nn.init.zeros_(self.net[-1].bias)

    @staticmethod
    def _alternating_mask(target_dim):
        return [(i % 2) for i in range(target_dim)]

    def _shift_log_scale(self, x, context):
        masked_x = x * self.mask
        params = self.net(torch.cat([masked_x, context], dim=-1))
        shift, log_scale = params.chunk(2, dim=-1)
        transform_mask = 1.0 - self.mask
        shift = shift * transform_mask
        log_scale = torch.tanh(log_scale) * self.scale_limit * transform_mask
        return shift, log_scale

    def forward(self, z, context):
        shift, log_scale = self._shift_log_scale(z, context)
        x = z * self.mask + (1.0 - self.mask) * (z * torch.exp(log_scale) + shift)
        logdet = log_scale.sum(dim=-1)
        return x, logdet

    def inverse(self, x, context):
        shift, log_scale = self._shift_log_scale(x, context)
        z = x * self.mask + (1.0 - self.mask) * ((x - shift) * torch.exp(-log_scale))
        logdet = -log_scale.sum(dim=-1)
        return z, logdet


def _qmc_normal(batch, n_samples, dim, dtype, device):
    """Randomized-QMC standard normals, shape (batch*n_samples, dim), row-major (obj, sample).

    The per-object integral we need is E[f(x)] over the flow's predictive distribution, estimated
    from n_samples draws. Plain `torch.randn` converges as 1/sqrt(n); a low-discrepancy (Sobol) set
    covers the unit cube far more evenly and converges nearer 1/n on smooth integrands, so the same
    accuracy needs far fewer draws.

    THE RANDOM SHIFT IS NOT OPTIONAL. If every object reused the SAME Sobol points, their quadrature
    errors would be perfectly correlated and would NOT average away over the ~1e6 objects -- that
    turns a variance into a BIAS, which is exactly the failure mode this estimator cannot tolerate.
    Giving each object its own uniform shift mod 1 (a randomly-shifted digital net) keeps the
    low-discrepancy structure WITHIN an object's n_samples while decorrelating objects, so the
    estimator stays unbiased and the object-average still converges.

    n_samples should be a power of two: Sobol's equidistribution guarantees hold on 2^k points and
    degrade for other counts.
    """
    eng = torch.quasirandom.SobolEngine(dimension=dim, scramble=True, seed=_QMC_SEED)
    u = eng.draw(n_samples).to(device=device, dtype=torch.float32)        # (n_samples, dim)
    shift = torch.rand(batch, 1, dim, device=device, dtype=torch.float32)  # per-object shift
    u = torch.remainder(u[None, :, :] + shift, 1.0)                       # (batch, n_samples, dim)
    # ndtri(0)= -inf, ndtri(1)=+inf; clamp just inside the open interval.
    u = u.clamp_(1e-7, 1.0 - 1e-7)
    z = torch.special.ndtri(u)
    return z.reshape(batch * n_samples, dim).to(dtype)


_QMC_SEED = 0


class ConditionalAffineFlow(nn.Module):
    def __init__(
        self,
        target_dim,
        context_dim,
        hidden_dim=256,
        n_layers=3,
        n_flows=8,
        scale_limit=3.0,
        activation="silu",
        **kwargs,  # ignore spline-only keys so a single config dict works for both
    ):
        super().__init__()
        if target_dim < 2:
            raise ValueError("target_dim must be >= 2 for affine coupling flows")
        if n_flows < 1:
            raise ValueError("n_flows must be >= 1")
        masks = []
        base = np.array([(i % 2) for i in range(target_dim)], dtype=np.float32)
        for i in range(n_flows):
            masks.append(base if i % 2 == 0 else 1.0 - base)
        self.target_dim = int(target_dim)
        self.context_dim = int(context_dim)
        self.layers = nn.ModuleList([
            ConditionalAffineCoupling(
                target_dim,
                context_dim,
                hidden_dim=hidden_dim,
                n_layers=n_layers,
                mask=mask,
                scale_limit=scale_limit,
                activation=activation,
            )
            for mask in masks
        ])

    def inverse(self, x, context):
        logdet = torch.zeros(x.shape[0], dtype=x.dtype, device=x.device)
        z = x
        for layer in reversed(self.layers):
            z, ldj = layer.inverse(z, context)
            logdet = logdet + ldj
        return z, logdet

    def forward(self, z, context):
        logdet = torch.zeros(z.shape[0], dtype=z.dtype, device=z.device)
        x = z
        for layer in self.layers:
            x, ldj = layer(x, context)
            logdet = logdet + ldj
        return x, logdet

    def log_prob(self, x, context):
        z, logdet = self.inverse(x, context)
        log_base = -0.5 * (z.pow(2) + np.log(2.0 * np.pi)).sum(dim=-1)
        return log_base + logdet

    def sample(self, context, n_samples=1, qmc=False):
        if n_samples < 1:
            raise ValueError("n_samples must be >= 1")
        if context.ndim != 2:
            raise ValueError("context must have shape (batch, context_dim)")
        batch = context.shape[0]
        expanded_context = context[:, None, :].expand(batch, n_samples, self.context_dim)
        flat_context = expanded_context.reshape(batch * n_samples, self.context_dim)
        if qmc:
            z = _qmc_normal(batch, n_samples, self.target_dim, context.dtype, context.device)
        else:
            z = torch.randn(batch * n_samples, self.target_dim,
                            dtype=context.dtype, device=context.device)
        flat_x, _ = self.forward(z, flat_context)
        return flat_x.reshape(batch, n_samples, self.target_dim)




class MeasurementModelBundle:
    def __init__(self, model, condition_preprocessor, target_transform, metadata=None, device="cpu"):
        self.device = torch.device(device)
        self.model = model.to(self.device)
        self.model.eval()
        self.condition_preprocessor = condition_preprocessor
        self.target_transform = target_transform
        self.metadata = metadata or {}

    def _context_from_frame(self, frame):
        context = self.condition_preprocessor.transform_frame(frame)
        return torch.as_tensor(context, dtype=torch.float32, device=self.device)

    def _targets_from_frame(self, frame):
        missing = [name for name in self.target_transform.target_names if name not in frame.columns]
        if missing:
            frame = add_measurement_target_features(frame.copy())
        targets = self.target_transform.transform_frame(frame)
        return torch.as_tensor(targets, dtype=torch.float32, device=self.device)

    @torch.no_grad()
    def log_prob(self, frame, batch_size=65536):
        values = []
        for start in range(0, len(frame), batch_size):
            batch = frame.iloc[start:start + batch_size]
            context = self._context_from_frame(batch)
            target = self._targets_from_frame(batch)
            values.append(self.model.log_prob(target, context).cpu().numpy())
        return np.concatenate(values) if values else np.array([], dtype=np.float32)

    @torch.no_grad()
    def sample(self, condition_frame, n_samples=1, batch_size=65536, qmc=False):
        samples = []
        for start in range(0, len(condition_frame), batch_size):
            batch = condition_frame.iloc[start:start + batch_size]
            context = self._context_from_frame(batch)
            draw = self.model.sample(context, n_samples=n_samples, qmc=qmc).cpu().numpy()
            flat = draw.reshape(-1, self.target_transform.dim)
            raw = self.target_transform.inverse_transform_array(flat)
            samples.append(raw.reshape(len(batch), n_samples, self.target_transform.dim))
        if not samples:
            return np.empty((0, n_samples, self.target_transform.dim), dtype=np.float32)
        return np.concatenate(samples, axis=0)

    def target_mean_and_gradient(
        self,
        frame,
        gradient_features: Optional[Iterable[str]] = None,
        n_samples=64,
        batch_size=2048,
    ):
        """Estimate d E[xhat] / d condition features with reparameterized draws.

        The estimate is Monte Carlo noisy but differentiable through the flow.
        Returned means are in the engineered target units, not standardized flow
        units.
        """
        if gradient_features is None:
            gradient_features = self.condition_preprocessor.feature_names
        gradient_features = list(gradient_features)
        feature_to_idx = {name: i for i, name in enumerate(self.condition_preprocessor.feature_names)}
        grad_idx = [feature_to_idx[name] for name in gradient_features]
        target_scale = torch.as_tensor(
            self.target_transform.scales,
            dtype=torch.float32,
            device=self.device,
        )
        target_mean = torch.as_tensor(
            self.target_transform.means,
            dtype=torch.float32,
            device=self.device,
        )

        means = []
        grads = []
        for start in range(0, len(frame), batch_size):
            batch = frame.iloc[start:start + batch_size]
            raw_context = self.condition_preprocessor.raw_tensor_from_frame(
                batch, self.device, requires_grad=True
            )
            context = self.condition_preprocessor.transform_tensor(raw_context)
            draws = self.model.sample(context, n_samples=n_samples)
            mean_standard = draws.mean(dim=1)
            mean_raw = mean_standard * target_scale + target_mean
            grad_columns = []
            for j in range(self.target_transform.dim):
                grad = torch.autograd.grad(
                    mean_raw[:, j].sum(),
                    raw_context,
                    retain_graph=j < self.target_transform.dim - 1,
                    create_graph=False,
                )[0]
                grad_columns.append(grad[:, grad_idx].detach().cpu().numpy())
            means.append(mean_raw.detach().cpu().numpy())
            grads.append(np.stack(grad_columns, axis=1))

        mean_arr = np.concatenate(means) if means else np.empty((0, self.target_transform.dim))
        grad_arr = np.concatenate(grads) if grads else np.empty((0, self.target_transform.dim, len(gradient_features)))
        grad_names = [
            f"dE_{target}_d{feature}"
            for target in self.target_transform.target_names
            for feature in gradient_features
        ]
        grad_df = pd.DataFrame(grad_arr.reshape(len(mean_arr), -1), columns=grad_names)
        mean_df = pd.DataFrame(mean_arr, columns=[f"E_{name}" for name in self.target_transform.target_names])
        return mean_df, grad_df


class ConditionalMeanFlow(nn.Module):
    """Explicit-conditional-mean density: p(x|c) = p_resid(x - mu(c) | c).

    A direct mean head mu(c) carries the conditional-mean RESPONSE (so it is NOT shrunk
    toward the marginal the way a pure flow's mean is).  This fixes the measured-shape
    response under-fit (M_model -> M_data) that drives the multiplicative shear bias.
    mu is linear by default (the OLS conditional mean is already an excellent fit); set
    mean_hidden>0 for an MLP head.

    *** mu IS NOT THE CONDITIONAL MEAN, AND p_resid IS NOT ZERO-CENTRED. ***  Only mu's
    SHAPE-DEPENDENCE is pinned; its LEVEL is unidentified, because the response loss
    constrains only DIFFERENCES mu(c+) - mu(c-) (any constant cancels) and the NLL
    constrains only the SUM mu + residual.  Neither constrains mu alone, so it drifts and
    the residual flow absorbs the offset.  Measured on the fiducial dom6x6 s501 checkpoint
    (WORKLOG 2026-08-04f, `scripts/diag_meanhead_identifiability.py`): <mu(g2)> = +5.01 in
    standardized units -- +1.79 in raw ellipticity, outside the physical range -- against a
    data mean of +0.01, cancelled by <resid> = -5.00.

    This is harmless for the response ONLY because the residual flow is blind to the shape
    features (`flow_drop_indices`), which makes d<x>/d(shape) == d mu/d(shape) exactly,
    whatever the level.  But it means: DO NOT read mu, or any per-object mean-head output,
    as a predicted mean, and do not plot it as one -- only differences of mu are meaningful.
    Code needing the actual model mean must sample the full model (as
    `MeasurementModelBundle.target_mean_and_gradient` does).
    """

    def __init__(self, target_dim, context_dim, base_flow="affine", mean_hidden=0,
                 mean_activation="silu", flow_drop_indices=None, **kwargs):
        super().__init__()
        self.target_dim = int(target_dim)
        self.context_dim = int(context_dim)
        # The residual flow can be made BLIND to selected context columns (e.g. the shape
        # features) so the shape->shape response is forced entirely into the explicit mean
        # head and cannot be re-absorbed/shrunk by the flow. keep_indices = the columns the
        # residual flow still sees (noise-scale features).
        drop = sorted(set(int(i) for i in (flow_drop_indices or [])))
        keep = [i for i in range(context_dim) if i not in drop]
        self.register_buffer("keep_indices", torch.as_tensor(keep, dtype=torch.long))
        flow_context_dim = len(keep)
        if base_flow == "affine":
            self.flow = ConditionalAffineFlow(target_dim=target_dim, context_dim=flow_context_dim, **kwargs)
        elif base_flow == "spline":
            from .spline_flow import ConditionalSplineFlow
            self.flow = ConditionalSplineFlow(target_dim=target_dim, context_dim=flow_context_dim, **kwargs)
        else:
            raise ValueError(f"Unknown base_flow {base_flow!r}")
        if mean_hidden and mean_hidden > 0:
            act = _activation(mean_activation)
            self.mean_net = nn.Sequential(
                nn.Linear(context_dim, mean_hidden), act(),
                nn.Linear(mean_hidden, target_dim))
        else:
            self.mean_net = nn.Linear(context_dim, target_dim)

    def _mu(self, context):
        return self.mean_net(context)

    def _flow_ctx(self, context):
        return context.index_select(1, self.keep_indices)

    def _shift(self, context, u=None):
        """Additive shift applied to the residual-flow draw / subtracted in log_prob.

        The BASE class ignores `u` and returns exactly mu(context), so every existing call
        site (and the fiducial arithmetic) is unchanged.  Subclasses that make the shift
        REALISATION-AWARE (ConditionalMeanFlowRA) use `u`, the per-draw residual on the
        `ra_indices` channels.  Callers that build a response by differencing mu across
        shifted contexts MUST go through `_shift(ctx, u)` -- see the trainer -- or the
        realisation-aware part of the response is silently left unsupervised.
        """
        return self._mu(context)

    @torch.no_grad()
    def set_ols_mean_and_freeze(self, context_std, target_std):
        """Fit the linear mean head by OLS on standardized (context, target) and freeze it.

        Pins the conditional mean to the data's best *linear* conditional mean E[x|c],
        a pure g=0 quantity.  With the residual flow kept blind to the shape features,
        the shape->shape response d<x>/d(shape) then equals the OLS data response M_data
        *by construction* and cannot be shrunk/re-absorbed by max-likelihood training.

        This is forward-model self-calibration derived entirely from the g=0 sample; it
        never uses the sheared-sim applied-shear truth (that would be a circular,
        illegitimate empirical m-removal).  Closure already shows recovery is unbiased
        given a faithful model, so pinning M_model == M_data targets the multiplicative
        bias at its root (the flow's conditional-mean under-fit).
        """
        if not isinstance(self.mean_net, nn.Linear):
            raise ValueError("OLS mean-freeze requires a linear mean head (mean_hidden=0)")
        C = np.asarray(context_std, dtype=np.float64)
        Y = np.asarray(target_std, dtype=np.float64)
        A = np.concatenate([C, np.ones((C.shape[0], 1), dtype=np.float64)], axis=1)
        sol, *_ = np.linalg.lstsq(A, Y, rcond=None)  # (context_dim+1, target_dim)
        W = sol[:-1, :].T.astype(np.float32)         # (target_dim, context_dim)
        b = sol[-1, :].astype(np.float32)            # (target_dim,)
        self.mean_net.weight.copy_(torch.as_tensor(W))
        self.mean_net.bias.copy_(torch.as_tensor(b))
        self.mean_net.weight.requires_grad_(False)
        self.mean_net.bias.requires_grad_(False)

    def log_prob(self, x, context):
        return self.flow.log_prob(x - self._mu(context), self._flow_ctx(context))

    def sample(self, context, n_samples=1, qmc=False):
        s = self.flow.sample(self._flow_ctx(context), n_samples=n_samples, qmc=qmc)
        return s + self._mu(context)[:, None, :]


class ConditionalMeanFlowRA(ConditionalMeanFlow):
    """REALISATION-AWARE mean head (design `mean_affine_ra`).

        p(x|c) = p_resid( x - mu(c) - A(c, u) | c ),      u = (x - mu(c))[ra_indices]

    THE DEFECT IT TARGETS.  In `ConditionalMeanFlow` the residual flow is deliberately blind to
    the shape features, so the WHOLE shear response lives in the linear/MLP mean head mu(c) and
    is added IDENTICALLY to every draw of an object.  Within one object every draw therefore
    carries the same response, fixed by its TRUE properties: the model cannot represent the fact
    that a particular measurement realisation came out faint/small and so has a collapsed
    response.  A(c, u) restores exactly that: an additive shift on the SHAPE channels whose value
    depends on the drawn photometry residual u (measured mag and log-size, target dims 2 and 3).

    TRIANGULAR BY CONSTRUCTION.  `ra_targets` (shape channels 0,1) and `ra_indices` (photometry
    channels 2,3) are disjoint, so A never moves the channels it reads.  The map
    r -> r - A(c, r[ra_indices]) is therefore triangular with unit diagonal: |det J| = 1 and the
    density needs NO log-det term.  The same disjointness makes the sampling inverse closed-form
    (the drawn residual's ra_indices channels are already the final ones), so `sample` costs one
    extra MLP pass and no iteration.

    EXACT REDUCTION.  `ra_net`'s output layer is zero-initialised, so A == 0 at init and both
    `log_prob` and `sample` are bit-identical to the parent class.  That makes a warm start from
    an existing `mean_affine` checkpoint exact (`load_state_dict(..., strict=False)`).

    SCOPE.  A is zero on channels 2,3 by construction, so the drawn mag and size -- and hence any
    moving measured-cut boundary -- are UNCHANGED.  This design addresses the response VALUE, not
    the selection/boundary channel.
    """

    def __init__(self, target_dim, context_dim, base_flow="affine", mean_hidden=0,
                 mean_activation="silu", flow_drop_indices=None,
                 ra_hidden=64, ra_activation="silu",
                 ra_indices=(2, 3), ra_targets=(0, 1), **kwargs):
        # SWALLOW TRAP. Both ConditionalMeanFlow and ConditionalAffineFlow end in a bare **kwargs,
        # so an unknown key reaches neither an error nor an effect: `ra_hiden=32` silently builds
        # the DEFAULT width, `ra_target=[2,3]` silently keeps ra_targets=(0,1). Nothing in the RA
        # namespace may be swallowed -- no legitimate flow kwarg starts with "ra".
        stray = sorted(k for k in kwargs if k.startswith("ra"))
        if stray:
            raise ValueError(
                f"unknown realisation-aware key(s) {stray} would be silently swallowed by the "
                "flow's **kwargs; valid RA keys are ra_hidden, ra_activation, ra_indices, "
                "ra_targets")
        super().__init__(target_dim=target_dim, context_dim=context_dim, base_flow=base_flow,
                         mean_hidden=mean_hidden, mean_activation=mean_activation,
                         flow_drop_indices=flow_drop_indices, **kwargs)
        ridx = [int(i) for i in ra_indices]
        rtgt = [int(i) for i in ra_targets]
        if not ridx or not rtgt:
            raise ValueError("ra_indices and ra_targets must be non-empty")
        if set(ridx) & set(rtgt):
            raise ValueError(
                f"ra_indices {ridx} and ra_targets {rtgt} must be DISJOINT -- the unit-Jacobian "
                "triangular argument fails if A moves a channel it reads")
        bad = [i for i in ridx + rtgt if i < 0 or i >= self.target_dim]
        if bad:
            raise ValueError(f"ra index/target out of range for target_dim={self.target_dim}: {bad}")
        if int(ra_hidden) <= 0:
            raise ValueError(
                "ra_hidden must be > 0 for flow_type='mean_affine_ra'; use flow_type='mean_affine' "
                "for the plain (realisation-blind) head")
        self.register_buffer("ra_indices", torch.as_tensor(ridx, dtype=torch.long))
        self.register_buffer("ra_targets", torch.as_tensor(rtgt, dtype=torch.long))
        self.ra_hidden = int(ra_hidden)
        act = _activation(ra_activation)
        self.ra_net = nn.Sequential(
            nn.Linear(context_dim + len(ridx), self.ra_hidden), act(),
            nn.Linear(self.ra_hidden, len(rtgt)))
        # ZERO-INIT the output layer: A == 0 at construction => exact reduction to the parent.
        nn.init.zeros_(self.ra_net[-1].weight)
        nn.init.zeros_(self.ra_net[-1].bias)

    def _A(self, context, u):
        """(batch, target_dim) additive shift, non-zero only on `ra_targets`.

        `u` is the realisation residual on `ra_indices` -- fed together with the context and
        NOTHING else.  Feeding the absolute drawn photometry mu(c)+u instead would make A's
        argument leg-dependent (mu moves between legs through the b_mag * e_int coupling) and
        break the "u is shear-independent" statement the common-random-number response rests on.
        """
        if u is None:
            raise ValueError(
                "ConditionalMeanFlowRA needs the realisation residual u on the ra_indices "
                "channels; a caller reached _A/_shift without one")
        raw = self.ra_net(torch.cat([context, u], dim=-1))
        zeros = torch.zeros(raw.shape[:-1] + (self.target_dim,), dtype=raw.dtype, device=raw.device)
        return zeros.index_add(-1, self.ra_targets, raw)

    def _shift(self, context, u=None):
        return self._mu(context) + self._A(context, u)

    @torch.no_grad()
    def set_ols_mean_and_freeze(self, context_std, target_std):
        raise NotImplementedError(
            "OLS mean-freeze is not defined for the realisation-aware head: freezing mu alone "
            "leaves A trainable and unsupervised. Use flow_type='mean_affine' for that path.")

    def log_prob(self, x, context):
        resid = x - self._mu(context)
        u = resid.index_select(-1, self.ra_indices)
        # unit Jacobian (triangular, ra_targets disjoint from ra_indices) -> no log-det term
        return self.flow.log_prob(resid - self._A(context, u), self._flow_ctx(context))

    def sample(self, context, n_samples=1, qmc=False):
        z = self.flow.sample(self._flow_ctx(context), n_samples=n_samples, qmc=qmc)
        batch, n, dim = z.shape
        # closed-form inverse: A does not touch ra_indices, so the drawn residual's ra_indices
        # channels ARE the final ones and u is read straight off z.
        u = z.index_select(-1, self.ra_indices).reshape(batch * n, -1)
        cflat = context[:, None, :].expand(batch, n, self.context_dim).reshape(batch * n, self.context_dim)
        a = self._A(cflat, u).view(batch, n, dim)
        return z + a + self._mu(context)[:, None, :]


def build_flow(model_config):
    """Construct the conditional flow from a config dict (dispatch on flow_type)."""
    cfg = dict(model_config)
    flow_type = cfg.pop("flow_type", "affine")
    # Training-only response-loss metadata may be saved with newer checkpoints.
    # It does not affect the density architecture.
    cfg.pop("response_difference", None)
    cfg.pop("response_error", None)
    # The OTHER half of the swallow trap: RA keys on a NON-RA flow_type. Those would be eaten by
    # the same **kwargs chain and the model would be built with NO realisation-aware head at all
    # -- the failure mode this whole design is trying to make impossible.
    if not flow_type.endswith("_ra"):
        stray = sorted(k for k in cfg if k.startswith("ra"))
        if stray:
            raise ValueError(
                f"flow_type={flow_type!r} does not build a realisation-aware head, but the config "
                f"carries {stray}; those keys would be silently ignored. Use flow_type "
                "'mean_affine_ra' / 'mean_spline_ra', or drop the keys.")
    if flow_type == "affine":
        return ConditionalAffineFlow(**cfg)
    if flow_type == "spline":
        from .spline_flow import ConditionalSplineFlow
        return ConditionalSplineFlow(**cfg)
    if flow_type in ("mean_affine", "mean_spline"):
        cfg["base_flow"] = "affine" if flow_type == "mean_affine" else "spline"
        return ConditionalMeanFlow(**cfg)
    # REALISATION-AWARE head. A distinct flow_type string, NOT a flag on mean_affine: the
    # double **kwargs (ConditionalMeanFlow -> ConditionalAffineFlow) silently swallows unknown
    # config keys, so a flag would be ignored by an older code copy instead of failing. With a
    # new string the `raise` below makes an older copy fail loudly.
    if flow_type in ("mean_affine_ra", "mean_spline_ra"):
        cfg["base_flow"] = "affine" if flow_type == "mean_affine_ra" else "spline"
        return ConditionalMeanFlowRA(**cfg)
    raise ValueError(f"Unknown flow_type {flow_type!r}")


def save_measurement_model(path, model, condition_preprocessor, target_transform, model_config, metadata=None):
    checkpoint = {
        "state_dict": model.state_dict(),
        "condition_preprocessor": condition_preprocessor.to_state(),
        "target_transform": target_transform.to_state(),
        "model_config": dict(model_config),
        "metadata": metadata or {},
    }
    torch.save(checkpoint, path)


def load_measurement_model(path, device="cpu"):
    try:
        checkpoint = torch.load(path, map_location=device, weights_only=False)
    except TypeError:
        checkpoint = torch.load(path, map_location=device)
    condition_preprocessor = TabularPreprocessor.from_state(checkpoint["condition_preprocessor"])
    target_transform = TargetStandardizer.from_state(checkpoint["target_transform"])
    model = build_flow(checkpoint["model_config"])
    model.load_state_dict(checkpoint["state_dict"])
    return MeasurementModelBundle(
        model,
        condition_preprocessor,
        target_transform,
        metadata=checkpoint.get("metadata", {}),
        device=device,
    )
