"""WHY is the flow's magnitude-cut selection response flat? Measure the one channel that carries it.

BACKGROUND. The Gold-V2 flow is never conditioned on g. Its ONLY shear channel into the measured
observables is the mean head's dependence on the intrinsic shape, and the residual flow is explicitly
blind to it (`--flow-blind-features e1_input_p e2_input_p`). During training that channel is PINNED
by the spin-2 orientation-coupling loss (lam_theta=500) to

    d<measured_mag_auto>/dg      = b_mag  * e_int
    d<measured_log_flux_radius>/dg = b_size * e_int

with b_mag/b_size read per (flux, size, crowd) cell from --coupling-npz. So the model's whole
moving-boundary selection response is generated by those two numbers. Globally the target file
carries b_size=0.490 but b_mag=0.025 -- a 19x weaker magnitude coupling.

Those targets were measured on the det_meas HALF-SHEAR sim at g=0.05. The selection figure evaluates
on constgold at g=+/-0.02. This script measures the SAME coefficients directly on constgold and on
the flow, so the three can be compared like for like:

    b_x = slope of [ x_plus - x_minus ] / (2g)  regressed on  p_int = e_int . ghat

(exactly the pinned quantity: with ghat=(1,0), Delta x = b_x * e_int * 2g). Reported globally and in
the coupling file's own (flux, size) cells.

It also reports, per cut threshold, the two factors the moving-boundary response actually factorises
into -- the density of objects AT the boundary and the boundary-local mean of p_int * (-Delta x) --
so a mismatch can be attributed to the wrong coupling vs the wrong measured distribution.

PART A additionally compares the TRAINING population to the constgold evaluation population under the
identical `source_select_selection(DEFAULT_SELECTION_CUTS)` both sides apply, to confirm the flow is
not being asked to extrapolate off its training support.

Nothing is trained or fitted. constgold stays EVAL-ONLY.
"""
from __future__ import annotations

import argparse
import glob
import os
import sys
import time

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.ipc as ipc
import torch

_HERE = os.path.dirname(os.path.abspath(__file__))
SBSI_ROOT = os.path.dirname(_HERE)
for _p in (SBSI_ROOT, _HERE):          # _HERE so eval_selection_intrinsic imports as a sibling
    if _p not in sys.path:
        sys.path.insert(0, _p)

from sbs_shear.measurement_model import load_measurement_model  # noqa: E402
from sbs_shear.preprocessing import (  # noqa: E402
    source_select_selection, DEFAULT_SELECTION_CUTS,
)
from eval_selection_intrinsic import build_base, prepare_legs, MEASURED, CROWD  # noqa: E402

TRAIN_CAT = ("/project/ls-gruen/users/zekang.zhang/sbsi_catalogues/"
             "det_meas_crowd_conc_g0.0_train_full.feather")
COUPLING = ("/home/z/Zekang.Zhang/SBSI/results/"
            "response_target_theta_coupling_rblend_c0-99_6x9x5.npz")


def qtable(name, d):
    """Quantile fingerprint of a population, printed one row per column."""
    print(f"  {name}")
    print(f"    {'column':>16} {'N':>12} {'p01':>8} {'p16':>8} {'p50':>8} {'p84':>8} {'p99':>8} "
          f"{'mean':>8}")
    for c, v in d.items():
        v = np.asarray(v, float)
        v = v[np.isfinite(v)]
        q = np.percentile(v, [1, 16, 50, 84, 99]) if len(v) else [np.nan] * 5
        print(f"    {c:>16} {len(v):>12,} {q[0]:>8.3f} {q[1]:>8.3f} {q[2]:>8.3f} {q[3]:>8.3f} "
              f"{q[4]:>8.3f} {np.mean(v) if len(v) else np.nan:>8.3f}")


def population_check(base, train_cat, train_max_rows, t0):
    """PART A: is the constgold eval population the same one the flow was trained on?

    Both sides apply source_select_selection(DEFAULT_SELECTION_CUTS) -- true mag in [18,28], true Re
    in [0.1,1.5], neighbour distance < 5" (or unneighboured). Identical cuts do NOT guarantee
    identical populations: the two sims can differ in depth and crowding. Compare the distributions.
    """
    print("\n" + "=" * 78)
    print("PART A -- training population vs constgold evaluation population")
    print("=" * 78, flush=True)
    print(f"  cuts applied on BOTH sides: DEFAULT_SELECTION_CUTS = {DEFAULT_SELECTION_CUTS}")
    print("    -> [1] true mag r_input_p in (18,28) ; [3] true Re_input_p in (0.1,1.5) ;"
          " [4] distance<5\" or ~neighbored")

    cols = ["r_input_p", "Re_input_p", "distance", "neighbored", "sersic_n_input_p"]
    parts, n = [], 0
    with ipc.open_file(pa.memory_map(train_cat)) as r:
        use = [c for c in cols if c in set(r.schema.names)]
        for bi in range(r.num_record_batches):
            b = pa.Table.from_batches([r.get_batch(bi)]).select(use).to_pandas()
            parts.append(b)
            n += len(b)
            if n >= train_max_rows:
                break
    tr = pd.concat(parts, ignore_index=True).iloc[:train_max_rows]
    del parts
    print(f"  training catalogue: {os.path.basename(train_cat)}  read {len(tr):,} rows "
          f"({time.time()-t0:.0f}s)", flush=True)
    tr = source_select_selection(tr, cuts=DEFAULT_SELECTION_CUTS)
    print(f"  after cuts: {len(tr):,}", flush=True)

    qtable("TRAINING (det_meas g=0 leg, the flow's own sample)",
           {c: tr[c] for c in ("r_input_p", "Re_input_p", "sersic_n_input_p")})
    qtable("CONSTGOLD (this evaluation)",
           {c: base[c] for c in ("r_input_p", "Re_input_p", "sersic_n_input_p")})
    print(f"    neighboured fraction: training {tr['neighbored'].mean():.3f}   "
          f"constgold {base['neighbored'].mean():.3f}")

    # how much of the eval sample sits outside the bulk of training support
    for c in ("r_input_p", "Re_input_p"):
        lo, hi = np.percentile(tr[c].to_numpy(float), [0.5, 99.5])
        out = float(np.mean((base[c].to_numpy(float) < lo) | (base[c].to_numpy(float) > hi)))
        print(f"    {c}: {out:.3%} of constgold outside training [p0.5,p99.5]=({lo:.3f},{hi:.3f})")
    del tr


def slope(dx, p):
    """b = Cov(dx, p)/Var(p): the pinned coupling coefficient, given dx already divided by 2g."""
    ok = np.isfinite(dx) & np.isfinite(p)
    if ok.sum() < 50:
        return np.nan, int(ok.sum())
    d, q = dx[ok], p[ok]
    v = q.var()
    return (float(np.cov(d, q, bias=True)[0, 1] / v) if v > 0 else np.nan), int(ok.sum())


def coupling_report(tag, dmag, dlsz, p_int, base, cz, g):
    """PART B/C: measured coupling vs the pinned target, globally and per (flux, size) cell."""
    bm, nm = slope(dmag / (2 * g), p_int)
    bs, ns = slope(dlsz / (2 * g), p_int)
    print(f"\n  [{tag}]  GLOBAL   b_mag = {bm:+.4f}   b_size = {bs:+.4f}   (N={nm:,})")
    print(f"           pinned    b_mag = {float(cz['b_mag_global']):+.4f}   "
          f"b_size = {float(cz['b_size_global']):+.4f}   <- target the flow was trained to")

    ef, es = cz["edges_flux"], cz["edges_size"]
    cnt = cz["counts"]                       # (nf, ns, nb)
    w = cnt.sum(axis=2)
    with np.errstate(invalid="ignore", divide="ignore"):
        tgt_m = (cz["coupling_mag"] * cnt).sum(axis=2) / np.where(w > 0, w, np.nan)
        tgt_s = (cz["coupling_size"] * cnt).sum(axis=2) / np.where(w > 0, w, np.nan)

    fi = np.clip(np.digitize(base["r_input_p"].to_numpy(float), ef[1:-1]), 0, len(ef) - 2)
    si = np.clip(np.digitize(base["Re_input_p"].to_numpy(float), es[1:-1]), 0, len(es) - 2)
    print(f"    {'true mag bin':>16} {'true Re bin':>14} {'N':>10} "
          f"{'b_mag':>8} {'pin':>8} | {'b_size':>8} {'pin':>8}")
    for a in range(len(ef) - 1):
        for b_ in range(len(es) - 1):
            m = (fi == a) & (si == b_)
            if m.sum() < 5000:
                continue
            bmv, _ = slope((dmag / (2 * g))[m], p_int[m])
            bsv, _ = slope((dlsz / (2 * g))[m], p_int[m])
            print(f"    {ef[a]:>7.2f}-{ef[a+1]:<8.2f} {es[b_]:>6.2f}-{es[b_+1]:<7.2f} "
                  f"{int(m.sum()):>10,} {bmv:>8.4f} {tgt_m[a, b_]:>8.4f} | "
                  f"{bsv:>8.4f} {tgt_s[a, b_]:>8.4f}")
    return bm, bs


def boundary_report(base, p_int, dmag, dlsz, g, mag_cuts, size_cuts, px):
    """PART D: the two factors the moving-boundary response factorises into, at each threshold.

    R_sel ~= density(T) * < p_int * (-Delta x) >_{x near T} / (2g) / keep_fraction
    Splitting it says whether a sim/model mismatch is the coupling (second factor) or the measured
    distribution (first factor).
    """
    print("\n" + "=" * 78)
    print("PART D -- moving-boundary decomposition on the SIM (constgold)")
    print("=" * 78)
    print(f"  {'cut':>12} {'keep%':>7} {'dens/unit':>10} {'<p*(-dx)>/2g':>14} "
          f"{'product':>10} {'R_sel exact':>12}")
    mag = base["measured_mag_auto_plus"].to_numpy(float)
    lsz = np.log(np.maximum(base["measured_flux_radius_plus"].to_numpy(float), 1e-6))
    for kind, thrs in (("mag", mag_cuts), ("size", size_cuts)):
        for c in thrs:
            if kind == "mag":
                x, dx, T, w, keep_hi = mag, dmag, float(c), 0.05, False
            else:
                x, dx, T, w = lsz, dlsz, float(np.log(float(c) / px)), 0.02
                keep_hi = True
            near = np.abs(x - T) < w
            dens = float(near.mean()) / (2 * w)
            drv = float(np.mean(p_int[near] * (-dx[near]))) / (2 * g) if near.sum() > 50 else np.nan
            if keep_hi:
                pp, pm = x > T, (x - dx) > T
            else:
                pp, pm = x < T, (x - dx) < T
            keep = 0.5 * (pp.mean() + pm.mean())
            exact = (p_int[pp].mean() - p_int[pm].mean()) / (2 * g)
            # keep-low: a POSITIVE dx pushes an object out of the sample, so the boundary term
            # enters with the opposite sign to the keep-high case.
            sgn = -1.0 if keep_hi else 1.0
            print(f"  {kind}{c:>8g} {keep*100:>7.2f} {dens:>10.4f} {drv:>+14.5f} "
                  f"{sgn*dens*drv/max(keep,1e-9):>+10.5f} {exact:>+12.5f}")


@torch.no_grad()
def flow_deltas(bundle, legs, n_samples, batch_size, flow_seed, chunk, n):
    """Per-object mean measured mag / log-size in each leg, common random numbers across legs."""
    out = {}
    for leg in (0, 1):
        mg = np.empty(n, dtype=np.float64)
        sz = np.empty(n, dtype=np.float64)
        for cs in range(0, n, chunk):
            sl = slice(cs, min(cs + chunk, n))
            torch.manual_seed(flow_seed + cs)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(flow_seed + cs)
            d = bundle.sample(legs[leg].iloc[sl], n_samples=n_samples, batch_size=batch_size)
            mg[sl] = np.nanmean(d[:, :, 2], axis=1)
            sz[sl] = np.nanmean(d[:, :, 3], axis=1)
        out[leg] = (mg, sz)
    return out[1][0] - out[0][0], out[1][1] - out[0][1]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ckpt-glob",
                    default="/project/ls-gruen/users/zekang.zhang/sbsi_caches/ablation/"
                            "measurement_flow_g0_ngmix_ablate_s2c_coupling_lt500_s50*_swaavg.pt")
    ap.add_argument("--n-ckpt", type=int, default=3, help="checkpoints to average for the flow side")
    ap.add_argument("--coupling-npz", default=COUPLING)
    ap.add_argument("--train-cat", default=TRAIN_CAT)
    ap.add_argument("--train-max-rows", type=int, default=4_000_000, help="as used in training")
    ap.add_argument("--min-case", type=int, default=40)
    ap.add_argument("--max-case", type=int, default=139)
    ap.add_argument("--mag-cuts", type=float, nargs="+", default=[24.5, 25.5, 26.0, 26.5])
    ap.add_argument("--size-cuts", type=float, nargs="+", default=[0.3, 0.5, 0.6, 0.7])
    ap.add_argument("--pixel-size", type=float, default=0.2)
    ap.add_argument("--n-samples", type=int, default=128)
    ap.add_argument("--batch-size", type=int, default=16384)
    ap.add_argument("--chunk", type=int, default=250_000)
    ap.add_argument("--flow-seed", type=int, default=12345)
    ap.add_argument("--model-max-rows", type=int, default=1_000_000)
    ap.add_argument("--subsample-seed", type=int, default=7)
    args = ap.parse_args()

    t0 = time.time()
    cz = np.load(args.coupling_npz, allow_pickle=True)
    print(f"coupling target: {os.path.basename(args.coupling_npz)}  "
          f"nominal_g={float(cz['nominal_g'])}  convention={str(cz['e_convention'])}", flush=True)

    base, p_int, r_tot_i, gh1, gh2, g = build_base(args.min_case, args.max_case, MEASURED,
                                                   CROWD, t0)
    print(f"  constgold g={g}", flush=True)

    population_check(base, args.train_cat, args.train_max_rows, t0)

    # ---- sim-side per-object shear-induced shifts ----
    dmag = (base["measured_mag_auto_plus"].to_numpy(float)
            - base["measured_mag_auto_minus"].to_numpy(float))
    frp = np.maximum(base["measured_flux_radius_plus"].to_numpy(float), 1e-6)
    frm = np.maximum(base["measured_flux_radius_minus"].to_numpy(float), 1e-6)
    dlsz = np.log(frp) - np.log(frm)

    print("\n" + "=" * 78)
    print("PART B -- orientation coupling MEASURED on constgold vs the pinned training target")
    print("=" * 78, flush=True)
    coupling_report("SIM constgold", dmag, dlsz, p_int, base, cz, g)

    boundary_report(base, p_int, dmag, dlsz, g, args.mag_cuts, args.size_cuts, args.pixel_size)

    # ---- flow side: does the flow deliver the pinned coupling? ----
    print("\n" + "=" * 78)
    print("PART C -- the SAME coupling, measured on the flow")
    print("=" * 78, flush=True)
    ckpts = sorted(glob.glob(args.ckpt_glob))[:args.n_ckpt]
    if not ckpts:
        print("  no checkpoints found -- skipping flow side")
        return
    device = "cuda" if torch.cuda.is_available() else "cpu"
    sub_rng = np.random.default_rng(args.subsample_seed)
    idx = np.arange(len(base))
    if len(idx) > args.model_max_rows:
        idx = np.sort(sub_rng.choice(idx, args.model_max_rows, replace=False))
    legs = prepare_legs(base, gh1, gh2, g, idx)
    sub = base.iloc[idx].reset_index(drop=True)
    pi = p_int[idx]
    print(f"  flow subsample {len(idx):,} on {device}, {len(ckpts)} ckpt(s) "
          f"({time.time()-t0:.0f}s)", flush=True)

    for c in ckpts:
        bundle = load_measurement_model(c, device=device)
        fm, fs = flow_deltas(bundle, legs, args.n_samples, args.batch_size, args.flow_seed,
                             args.chunk, len(idx))
        coupling_report(f"FLOW {os.path.basename(c).split('_')[-2]}", fm, fs, pi, sub, cz, g)
        print(f"    ({time.time()-t0:.0f}s)", flush=True)
        del bundle
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    print("\nDIAG_SELECTION_CHANNELS_DONE", flush=True)


if __name__ == "__main__":
    main()
